colors: 256
features:
  browser: ''
  editor: ''
  emoji: true
  markdown: true
  notification: ''
  pictures: true
icons:
  alarm_snooze: "\uFB8C"
  block: "\u258C"
  block_bottom: "\u2598"
  block_top: "\u2596"
  channel: "\uF198"
  divider: "\uE0B1"
  edit: "\uF040"
  email: "\uF42F"
  full_divider: "\uE0B0"
  full_star: "\uF005"
  heart: "\uF004"
  keyboard: "\uF11C"
  line_star: "\uF006"
  offline: "\uF10C"
  online: "\uF111"
  person: "\uF415"
  phone: "\uF095"
  pin: "\uF435"
  private_channel: "\uF023"
  skype: "\uF17E"
  snooze: "\uF9B1"
  square: "\uF445"
  status: "\uF075"
  timezone: "\uF0AC"
keymap:
  compose_in_editor: meta i
  cursor_down: j
  cursor_left: h
  cursor_right: l
  cursor_up: k
  delete_message: d
  edit_message: e
  get_permalink: r
  go_to_chatbox: c
  go_to_profile: p
  go_to_sidebar: esc
  open_quick_switcher: ctrl k
  quit_application: q
  set_edit_topic_mode: ctrl t
  set_insert_mode: i
  set_snooze: ctrl d
  toggle_sidebar: s
  toggle_thread: t
  yank_message: y
logging: {}
sidebar:
  max_users: 20
  width: 25
theme: default
